project:
  type: website

website:
  title: "Personal_Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  
  page-footer:
    right: "&copy; 2024, Sizhuo Tian"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

